cache:
  paths:
    - /root/.cache
    - /root/.m2
image: ubuntu:20.10

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - apt-get update && apt-get install -y maven openjdk-15-jdk inkscape wget
    - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /opt/appimagetool
    - chmod +x /opt/appimagetool
    - (cd /opt/; ./appimagetool --appimage-extract)
    - mv /opt/squashfs-root /opt/appimagetool.AppDir
    - ln -s /opt/appimagetool.AppDir/AppRun appimagetool-x86_64.AppImage
    - mvn install -e -P full
  artifacts:
    paths:
      - merman1-x86_64.AppImage
      - webviewsyntaxexamples/target
      - jfxeditor1/target

pages:
  stage: deploy
  only:
    - master
  script:
    - mkdir public
    - cp webviewsyntaxexamples/target/webviewsyntaxexamples-0.0.0/webviewsyntaxexamples/webviewsyntaxexamples.js public/entry.js
    - cp webviewsyntaxexamples/src/main/java/main_dev.html public/index.html
  artifacts:
    paths:
      - public